name: Format generated files

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

jobs:
  run:
    name: Write structured data as a message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Start the Slack workflow
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
            "text": "github webhook triggered",
            }
