- name: Send GitHub Action data to a Slack workflow
  uses: slackapi/slack-github-action@v2.1.0
  with:
    payload-delimiter: "_"
    webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    webhook-type: webhook-trigger